spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.91:3306/sell?characterEncoding=utf-8&useSSL=false
env: test
