spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: d:gLMWru>68y
    url: jdbc:mysql://192.168.1.91:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.91:8761/eureka/
env: test
